### ISSUE TITLE
是否有使用的demo给一个的呀？

### ISSUE THREAD

**Issue by yuxingfafu** [staven630/miniprogram-city-picker#2]
是否有使用的demo给一个的呀？我这边使用的时候，一进入界面，就弹出那个地区选择框了，不知道是哪里使用的不对，能麻烦给个使用的demo么？多写

**Comment by staven630** [comment]
demo分支。https://github.com/staven630/wx-city-picker/tree/demo

**Comment by yuxingfafu** [comment]
您好，demo分支下来下来跑不起来呀，你那边可以跑么？

**Comment by staven630** [comment]
可以的
